In [20]:
import numpy as np

In [21]:
a = np.array([1,2,3,4])
print("a:\n", a)

a:
 [1 2 3 4]


In [22]:
b = np.array([[1,2], [3,4]])
print("b:\n", b)

b:
 [[1 2]
 [3 4]]


In [24]:
a.shape

(4,)

In [23]:
b.shape

(2, 2)

In [26]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [25]:
b.reshape(4)

array([1, 2, 3, 4])