NUMPY

In [42]:
import numpy as np

In [43]:
# 1D
a = np.array([1,2,3,4])
print("a:\n", a)

a:
 [1 2 3 4]


In [44]:
# 2D
b = np.array([[1,2], [3,4]])
print("b:\n", b)

b:
 [[1 2]
 [3 4]]


In [45]:
a.shape

(4,)

In [46]:
b.shape

(2, 2)

In [47]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [48]:
b.reshape(4)

array([1, 2, 3, 4])

In [49]:
# Data Types
c= np.array([[1,2,3],[4,"test",6]])
print(c.dtype)
print(type(c))

<U21
<class 'numpy.ndarray'>


In [50]:
# shape, number to fill
d= np.full((2,3),5)
print("full",d)

# shape
d= np.zeros((4))
print("zeroes",d)

# shape
d= np.ones((4,2))
print("ones",d)

# start,end,step
d= np.arange(1,5,2) 
print("arange",d)

# start,end,no.of values
d= np.linspace(1,5,2) 
print("linspace",d)

full [[5 5 5]
 [5 5 5]]
zeroes [0. 0. 0. 0.]
ones [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
arange [1 3]
linspace [1. 5.]


In [52]:
# Transpose
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [51]:
# Reshape does not change original array and length should be same

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Reshape into a 2x3 array
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [53]:
# Resize changes original array and it fills with 0 if shape is greater than before

arr = np.array([1, 2, 3])
arr.resize(5)  # Resize to 5 elements, filling with zeros
print(arr)

[1 2 3 0 0]
