NUMPY

In [1]:
import numpy as np

In [2]:
# 1D
a = np.array([1,2,3,4])
print("a:\n", a)

a:
 [1 2 3 4]


In [3]:
# 2D
b = np.array([[1,2], [3,4]])
print("b:\n", b)

b:
 [[1 2]
 [3 4]]


In [4]:
a.shape

(4,)

In [5]:
b.shape

(2, 2)

In [6]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [7]:
b.reshape(4)

array([1, 2, 3, 4])

In [8]:
# Data Types
c= np.array([[1,2,3],[4,"test",6]])
print(c.dtype)
print(type(c))

<U21
<class 'numpy.ndarray'>


In [9]:
# shape, number to fill
d= np.full((2,3),5)
print("full",d)

# shape
d= np.zeros((4))
print("zeroes",d)

# shape
d= np.ones((4,2))
print("ones",d)

# start,end,step
d= np.arange(1,5,2) 
print("arange",d)

# start,end,no.of values
d= np.linspace(1,5,2) 
print("linspace",d)

full [[5 5 5]
 [5 5 5]]
zeroes [0. 0. 0. 0.]
ones [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
arange [1 3]
linspace [1. 5.]


In [10]:
# Transpose
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
# Reshape does not change original array and length should be same

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Reshape into a 2x3 array
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [12]:
# Resize changes original array and it fills with 0 if shape is greater than before

arr = np.array([1, 2, 3])
arr.resize(5)  # Resize to 5 elements, filling with zeros
print(arr)

[1 2 3 0 0]


In [13]:
# save data in numpy in a file
arr = np.array([1, 2, 3])
np.save('test.npy',arr)

In [14]:
arr= np.load("test.npy")
print("load from npy file:",arr)

load from npy file: [1 2 3]


In [15]:
# save data in csv in a file
arr = np.array([1, 2, 3])
np.savetxt('test.csv',arr,delimiter=",")

In [16]:
arr= np.loadtxt("test.csv")
print("load from csv file:",arr)

load from csv file: [1. 2. 3.]
